-- write a game, to guess a number in range 1 to 10
-- the game will ask you to guess a number
-- if you guess right, you win
-- if you guess wrong, it will tell you if your guess is too high or too low
-- you have 3 chances to guess
-- if you run out of chances, you lose
-- if you win, you can play again
-- if you lose, you can play again
-- if you want to quit, you can quit
-- if you want to cheat, you can cheat
-- if you cheat, you will lose
-- if you cheat, you can play again

-- 1. ask the user to guess a number
-- 2. check if the guess is right
-- 3. if the guess is right, tell the user they won
--
--
--
-- ok, lets write the code
--
-- As the rules are above, now start writing the code

-- 1. ask the user to guess a number
